export const site = {
  businessName: "Kōra Studio Beauty",
  logoLineOne: "Kōra Studio",
  logoLineTwo: "Relax & Beauty",
  tagline: "Cosmetología, cejas, pestañas y relax en Nueva Córdoba",
  shortDescription: "Belleza y bienestar en Nueva Córdoba.",
  aboutText:
    "En Kōra combinamos cosmetología, belleza y relax en un ambiente tranquilo, con atención personalizada y resultados naturales.",
  heroTitle: "Cuidado facial, cejas, pestañas y relax en Nueva Córdoba",
  heroSubtitle: "Un espacio para cuidar tu piel, realzar tu mirada y regalarte una pausa.",
  heroNote: "Atención con cita previa · Obispo Oro 351",
  heroCtaPrimary: "Reservar turno",
  heroCtaSecondary: "Ver servicios",
  servicesIntro: "Tratamientos breves para piel, mirada y relax.",
  aboutEyebrow: "Sobre la marca",
  aboutTitle: "Un espacio para cuidarte con calma",
  galleryEyebrow: "Galería",
  galleryTitle: "Un espacio pensado para tu momento de cuidado",
  galleryDescription: "Ambiente cálido, detalles simples y fotos reales del estudio.",
  faqEyebrow: "Preguntas frecuentes",
  faqTitle: "Preguntas frecuentes",
  faqDescription: "Respuestas cortas para reservar sin vueltas.",
  contactEyebrow: "Ubicación y contacto",
  contactTitle: "Estamos en Nueva Córdoba",
  contactDescription: "Obispo Oro 351, oficina 3.",
  footerDescription: "Belleza y bienestar en Nueva Córdoba.",
  whatsappNumber: "5493517657141",
  whatsappDisplay: "+54 9 351 765 7141",
  whatsappMessage: "Hola, quiero consultar por un turno.",
  whatsappUrl: "https://wa.me/543517657141?text=Hola%2C%20quiero%20consultar%20por%20un%20turno.",
  instagramUrl: "https://www.instagram.com/kora.studioks",
  tiktokUrl: "https://www.tiktok.com/@kora.beautystudio",
  mapsUrl:
    "https://www.google.com/maps/search/?api=1&query=Obispo%20Oro%20351%20oficina%203%2C%20Nueva%20C%C3%B3rdoba%2C%20C%C3%B3rdoba%2C%20Argentina",
  mapsEmbedUrl:
    "https://www.google.com/maps?q=Obispo%20Oro%20351%20oficina%203%2C%20Nueva%20C%C3%B3rdoba%2C%20C%C3%B3rdoba%2C%20Argentina&output=embed",
  address: "Obispo Oro 351, oficina 3. Nueva Córdoba, Córdoba Capital, Argentina.",
  addressShort: "Obispo Oro 351, oficina 3.",
  locationLabel: "Nueva Córdoba, Córdoba Capital",
  availability: "Atención con cita previa",
  bookingNote: "Coordiná por WhatsApp",
  navigation: [
    { label: "Inicio", href: "#inicio" },
    { label: "Servicios", href: "#servicios" },
    { label: "Sobre la marca", href: "#sobre" },
    { label: "Galería", href: "#galeria" },
    { label: "Preguntas", href: "#faq" },
    { label: "Ubicación", href: "#ubicacion" },
  ],
  footerNavigation: [
    { label: "Servicios", href: "#servicios" },
    { label: "Sobre la marca", href: "#sobre" },
    { label: "Galería", href: "#galeria" },
    { label: "Contacto", href: "#contacto" },
  ],
  trustPoints: [
    "Cosmetología y cosmiatría",
    "Resultados sutiles",
    "Atención con cita previa",
  ],
  contactPoints: [
    "Obispo Oro 351, oficina 3",
    "Nueva Córdoba, Córdoba Capital",
    "Atención con cita previa",
  ],
  socialLinks: [
    { label: "WhatsApp", href: "https://wa.me/543517657141?text=Hola%2C%20quiero%20consultar%20por%20un%20turno.", icon: "whatsapp" },
    { label: "Instagram", href: "https://www.instagram.com/kora.studioks", icon: "instagram" },
    { label: "TikTok", href: "https://www.tiktok.com/@kora.beautystudio", icon: "tiktok" },
  ],
} as const;

export const services = [
  {
    title: "Limpiezas faciales",
    description: "Protocolos para limpiar, renovar e iluminar la piel.",
    image: "/images/cliente/servicio-limpieza-facial.jpg",
    alt: "Tratamiento de limpieza facial en Kōra Studio Beauty",
    accent: "bg-[#6f7a5a]",
    imagePosition: "object-center",
  },
  {
    title: "Limpieza Glass Skin",
    description: "Piel luminosa, fresca y con efecto glow.",
    image: "/images/cliente/servicio-glass-skin.jpg",
    alt: "Tratamiento Glass Skin para una piel luminosa",
    accent: "bg-[#758063]",
    imagePosition: "object-center object-top",
  },
  {
    title: "Hydralips",
    description: "Hidratación y cuidado para labios.",
    image: "/images/cliente/servicio-hydralips.jpg",
    alt: "Tratamiento Hydralips para labios hidratados",
    accent: "bg-[#b7a58a]",
    imagePosition: "object-center",
  },
  {
    title: "Cejas",
    description: "Perfilado y diseño para enmarcar la mirada.",
    image: "/images/cliente/servicio-cejas.jpg",
    alt: "Servicio de cejas con perfilado y diseño",
    accent: "bg-[#3e4634]",
    imagePosition: "object-center object-top",
  },
  {
    title: "Pestañas",
    description: "Lifting y tinte para realzar la mirada.",
    image: "/images/cliente/servicio-pestanas.jpg",
    alt: "Lifting y tinte de pestañas",
    accent: "bg-[#6f7a5a]",
    imagePosition: "object-center",
  },
  {
    title: "Masajes relajantes",
    description: "Masajes para bajar tensiones y desconectar.",
    image: "/images/cliente/servicio-masajes.jpg",
    alt: "Masaje relajante en un espacio de bienestar",
    accent: "bg-[#e8dccb]",
    imagePosition: "object-center object-top",
  },
] as const;

export const gallery = [
  {
    title: "Cabina",
    description: "Espacio cálido y sereno.",
    image: "/images/cliente/galeria-cabina.jpg",
    alt: "Cabina de atención de Kōra Studio Beauty",
    span: "lg:col-span-2 lg:row-span-2",
    imagePosition: "object-center",
  },
  {
    title: "Cuidado facial",
    description: "Detalle y limpieza en primer plano.",
    image: "/images/cliente/servicio-limpieza-facial.jpg",
    alt: "Cuidado facial en Kōra Studio Beauty",
    span: "",
    imagePosition: "object-center",
  },
  {
    title: "Productos",
    description: "Texturas y productos seleccionados.",
    image: "/images/cliente/galeria-productos.jpg",
    alt: "Productos de belleza y cuidado en Kōra Studio Beauty",
    span: "",
    imagePosition: "object-center",
  },
  {
    title: "Relax",
    description: "Calma, luz y una estética natural.",
    image: "/images/cliente/galeria-detalles.jpg",
    alt: "Detalles decorativos y de ambiente en Kōra Studio Beauty",
    span: "lg:col-span-2",
    imagePosition: "object-center object-top",
  },
] as const;

export const faqs = [
  {
    question: "¿Cómo reservo un turno?",
    answer: "Escribinos por WhatsApp o Instagram y coordinamos tu turno.",
  },
  {
    question: "¿Dónde están ubicadas?",
    answer: "En Nueva Córdoba, Obispo Oro 351, oficina 3.",
  },
  {
    question: "¿La atención es con turno previo?",
    answer: "Sí, trabajamos con cita previa.",
  },
  {
    question: "¿Qué tratamiento me conviene si es mi primera vez?",
    answer: "Consultanos y te orientamos según lo que quieras cuidar.",
  },
] as const;
